### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by RyuseiNono** [RyuseiNono/furima-26476#9]
# URL
https://furima-26476.herokuapp.com
# Basic認証
```
id : admin
password : 2222
```
# 出品者用アカウント
```
email : ichiro@furima.com
password : furima1
```
# 購入者用アカウント
```
email : jiro@furima.com
password : furima2
```
# 購入用カード情報
```
カード番号 : 4242424242424242
有効期限 : 12/23
セクキュリティコード : 123
```

**Comment by naru6117** [comment]
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/49669977/101881286-89276580-3bd7-11eb-9991-9b2cafdd448e.png)

RyuseiNonoさん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
